const CRYPTOCURRENCIES = [
  {
    id: 'BTC',
    name: 'Bitcoin',
    symbol: 'BTCBUSD',
    iconCode: 1,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://blockchair.com/bitcoin',
    value: 'BTCBUSD',
    label: 'BTCBUSD',
  },
  {
    id: 'ETH',
    name: 'Etherium',
    symbol: 'ETHBUSD',
    iconCode: 1027,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://etherscan.io',
    value: 'ETHBUSD',
    label: 'ETHBUSD',
  },
  {
    id: 'BNB',
    name: 'BNB',
    symbol: 'BNBBUSD',
    iconCode: 1839,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://bscscan.com',
    value: 'BNBBUSD',
    label: 'BNBBUSD',
  },
  {
    id: 'XRP',
    name: 'XRP',
    symbol: 'XRPBUSD',
    iconCode: 52,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://xrpscan.com',
    value: 'XRPBUSD',
    label: 'XRPBUSD',
  },
  {
    id: 'DOGE',
    name: 'Dogecoin',
    symbol: 'DOGEBUSD',
    iconCode: 74,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://blockchair.com/dogecoin',
    value: 'DOGEBUSD',
    label: 'DOGEBUSD',
  },
  {
    id: 'MATIC',
    name: 'Polygon',
    symbol: 'MATICBUSD',
    iconCode: 3890,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://polygonscan.com',
    value: 'MATICBUSD',
    label: 'MATICBUSD',
  },
  {
    id: 'SOL',
    name: 'Solana',
    symbol: 'SOLBUSD',
    iconCode: 5426,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://explorer.solana.com',
    value: 'SOLBUSD',
    label: 'SOLBUSD',
  },
  {
    id: 'SHIB',
    name: 'Shiba Inu',
    symbol: 'SHIBBUSD',
    iconCode: 5994,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer:
      'https://etherscan.io/token/0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce',
    value: 'SHIBBUSD',
    label: 'SHIBBUSD',
  },
  {
    id: 'APE',
    name: 'ApeCoin',
    symbol: 'APEBUSD',
    iconCode: 18876,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer:
      'https://etherscan.io/token/0x4d224452801aced8b2f0aebe155379bb5d594381',
    value: 'APEBUSD',
    label: 'APEBUSD',
  },
  {
    id: 'NEAR',
    name: 'NEAR Protocol',
    symbol: 'NEARBUSD',
    iconCode: 6535,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://explorer.near.org',
    value: 'NEARBUSD',
    label: 'NEARBUSD',
  },
  {
    id: 'LUNC',
    name: 'Terra Classic',
    symbol: 'LUNCBUSD',
    iconCode: 4172,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://finder.terra.money/classic',
    value: 'LUNCBUSD',
    label: 'LUNCBUSD',
  },
  {
    id: 'LUNA',
    name: 'Terra',
    symbol: 'LUNABUSD',
    iconCode: 20314,
    price: 0,
    prevPrice: 0,
    highPrice: 0,
    lowPrice: 0,
    explorer: 'https://finder.terra.money',
    value: 'LUNABUSD',
    label: 'LUNABUSD',
  },
];

export default CRYPTOCURRENCIES;
